# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: BackstopJs Automation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm install -g backstopjs
    - run: npm start
    - run: npm run reference
    - id: test
      run: npm run test
      continue-on-error: true
#if: steps.example.exitcode > 0   

uses: mrdoodles/issue-action@v1

with:

  token: ${{ secrets.GITHUB_TOKEN }}

  title: Some Issue Title

  body: Some Issue Body

  assignees: |

    mrdoodles

    alialaa

#     - name: Test marketplace action
#       uses: PavanMudigonda/html-reporter-github-pages@v1.0
#       id: test-report
#       with:
#         test_results: backstop_data
#         gh_pages: gh-pages
#         results_history: html_report
        
    - name: Publish Github Pages
      if: ${{ always() }}
      uses: peaceiris/actions-gh-pages@v3.8.0
      with:
        github_token: ${{ secrets.GT }}
        publish_branch: gh-pages
        publish_dir: backstop_data/
        keep_files: true 
      
    - run: npm run approve
